config/routes.rb
Rails.application.routes.draw do
  resources :types
  resources :markers
  resources :categories


  get 'marker_category/' , to: 'categories#marker_category'


  root 'markers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/marker.rb
class Marker < ApplicationRecord
    belongs_to :category
    belongs_to :type




end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  before_action :set_marker, only: %i[ show edit update destroy ]

  # GET /markers or /markers.json
  def index
    @markers = Marker.all
    @marker = Marker.new
  end

  # GET /markers/1 or /markers/1.json
  def show
    @types = Type.all

  end

  # GET /markers/new
  def new
    @marker = Marker.new
  end



  # GET /markers/1/edit
  def edit
    @types = Type.all
    @categories = Category.all
  end

  # POST /markers or /markers.json
  def create
    @marker = Marker.new(marker_params)
    respond_to do |format|
      if @marker.save

        format.html { redirect_to @marker, notice: "Marker was successfully created." }
        format.json { render :show, status: :created, location: @marker }
        format.js {render :create}
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end
    @types = Type.all

  end

  # PATCH/PUT /markers/1 or /markers/1.json
  def update
    respond_to do |format|
      if @marker.update(marker_params)
        format.html { redirect_to @marker, notice: "Marker was successfully updated." }
        format.json { render :show, status: :ok, location: @marker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end
    @types = Type.all

  end

  # DELETE /markers/1 or /markers/1.json
  def destroy
    @types = Type.all
    @marker.destroy
    respond_to do |format|
      format.html { redirect_to markers_url, notice: "Marker was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marker
      @marker = Marker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def marker_params
      params.require(:marker).permit(:url, :name, :type_id, :category_id )
    end

    def category_params
      params.require(:category)
    end
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/views/markers/_form.html.erb
<%= form_with(model: marker, remote: true) do |form| %>
  <% if marker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(marker.errors.count, "error") %> prohibited this marker from being saved:</h2>
      <ul>
        <% marker.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%# nostros %>
  <div class="field">
    <%= form.label :name, 'Nombre del marcador' %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :url, "Ingrese URL" %>
    <%= form.url_field :url  %>
  </div>
  <div class="field">
    <%= form.label :type_id, 'Tipo' %>
    <%= form.select :type_id, Type.all.collect {|t| [t.name, t.id]}, {} ,id: :marker_type_id  %>
  </div>
  <div class="field">
    <%= form.label :category_id, 'Categoria' %>
    <%= form.select :category_id, Category.all.collect {|c| [c.name, c.id]}, {} ,id: :marker_category_id  %>
  </div>
  <div class="actions">
    <%= form.submit data: { confirm: '¿estas seguro?' }  %>
  </div>
<% end %>

app/views/markers/_marker.html.erb
<tr id="marker_<%= marker.id%>">
  <td><%= marker.name %></td>
  <td><%= marker.type.name %></td>
  <td><%= marker.category.name %></td>
  <td><%= marker.url %></td>
  <td><%= link_to 'Show', marker %></td>
  <td><%= link_to 'Edit', edit_marker_path(marker) %></td>
  <td><%= link_to 'Destroy', marker, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
</tr>

app/views/markers/create.js.erb
document.querySelector('tbody').insertAdjacentHTML('beforeend', '<%= j render @marker %>') 

app/views/markers/edit.html.erb
<h1>Editing Marker</h1>

<%= render 'form', marker: @marker %>

<%= link_to 'Show', @marker %> |
<%= link_to 'Back', markers_path %>

app/views/markers/index.html.erb
<p id="notice"><%= notice %></p>
<%# <%= render 'shared/navbar' %> 
<%= render 'markers/form', marker: @marker %>
<h1>Markers</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Category</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @markers.each do |marker| %>
      <%= render 'markers/marker', marker: marker  %>
    <% end %>
  </tbody>
</table>
<br>

app/views/markers/new.html.erb
<h1>New Marker</h1>

<%= render 'form', marker: @marker %>

<%= link_to 'Back', markers_path %>

app/views/markers/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @marker.name %>
</p>
<p>
  <strong>Url:</strong>
  <%= @marker.url %>
</p>
<p>
  <strong>Type:</strong>
  <%= @marker.type.name %>
</p>
<p>
  <strong>Category:</strong>
  <%= @marker.category.name %>
</p>
<%= link_to 'Edit', edit_marker_path(@marker) %> |
<%= link_to 'Back', markers_path %>